#!/usr/bin/env python3
"""Generate the extended portable Clean Language file from the skill source.

Reads cleanlanguage/SKILL.md and its references and writes a single
self-contained rendering, site/downloads/cleanlanguage.md, for pasting or
attaching to an assistant that cannot install a skill. The file is generated,
never hand-edited; the sync gate checks it byte-for-byte.

Modes:
  (default)   write site/downloads/cleanlanguage.md atomically
  --embed     also rewrite the <pre id="instructions-text"> block in
              site/instructions/index.html with the HTML-escaped content
  --check     regenerate in memory, byte-compare the file and the embed,
              print the first difference, and exit 1 on any drift
"""
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILL = os.path.join(ROOT, "cleanlanguage", "SKILL.md")
REFDIR = os.path.join(ROOT, "cleanlanguage", "references")
OUT = os.path.join(ROOT, "site", "downloads", "cleanlanguage.md")
PAGE = os.path.join(ROOT, "site", "instructions", "index.html")

OPENING = ("This is the Clean Language skill, written out as rules. Apply it "
           "to the writing in this conversation unless I tell you not to.")
MARKER = ("(Generated from cleanlanguage/SKILL.md and its references by "
          "tools/build-portable-text.py. Do not edit this file by hand.)")

# Reference consult order, and the prose pointer each inline link becomes.
REFS = [
    ("anti-patterns.md", "Anti-patterns", "the Anti-patterns section below"),
    ("context-modes.md", "Context modes", "the Context modes section below"),
    ("qa-checklist.md", "Quality checklist", "the Quality checklist section below"),
    ("examples.md", "Examples", "the Examples section below"),
]


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def strip_frontmatter(text):
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end == -1:
            fail("SKILL.md frontmatter is not closed")
        return text[end + 5:]
    return text


def fail(msg):
    sys.stderr.write("build-portable-text: %s\n" % msg)
    sys.exit(1)


def demote_headings(text):
    # Each reference keeps one document; demote so the whole file has one H1.
    out = []
    for line in text.split("\n"):
        m = re.match(r"^(#{1,6}) ", line)
        if m:
            line = "#" + line
        out.append(line)
    return "\n".join(out)


def generate():
    skill = read(SKILL)
    body = strip_frontmatter(skill)
    lines = body.split("\n")
    # The metadata block: the contiguous run of "Key: value" lines after the H1.
    # Body starts with "# Clean Language"; find it and the metadata that follows.
    try:
        h1 = next(i for i, l in enumerate(lines) if l.strip() == "# Clean Language")
    except StopIteration:
        fail("SKILL.md has no '# Clean Language' heading")
    meta = []
    j = h1 + 1
    while j < len(lines) and lines[j].strip() == "":
        j += 1
    while j < len(lines) and re.match(r"^[A-Za-z][A-Za-z ]*:\s", lines[j]):
        meta.append(lines[j])
        j += 1
    if not meta:
        fail("SKILL.md metadata block not found after the heading")
    # The rest of the body after the metadata block is the skill proper.
    rest = "\n".join(lines[j:]).lstrip("\n")
    # Rewrite the inline reference links to prose pointers.
    for fname, _title, pointer in REFS:
        rest = rest.replace("[references/%s](references/%s)" % (fname, fname), pointer)
    if "](references/" in rest:
        fail("an unrewritten references/ link remains in the skill body")
    # The reference appendix, headings demoted one level, in consult order.
    appendix = []
    for fname, _title, _pointer in REFS:
        ref = read(os.path.join(REFDIR, fname)).rstrip("\n")
        appendix.append(demote_headings(ref))
    parts = [
        OPENING,
        "",
        "# Clean Language",
        "",
        "\n".join(meta),
        "",
        MARKER,
        "",
        rest.rstrip("\n"),
        "",
        "\n\n".join(appendix),
    ]
    return "\n".join(parts).rstrip("\n") + "\n"


def embed_html(content):
    return html.escape(content, quote=False)


def write_atomic(path, text):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    os.replace(tmp, path)


PRE_RE = re.compile(
    r'(<pre id="instructions-text"[^>]*>)(.*?)(</pre>)', re.DOTALL)


def embed(content):
    page = read(PAGE)
    if not PRE_RE.search(page):
        fail("could not find the <pre id=\"instructions-text\"> block")
    new = PRE_RE.sub(lambda m: m.group(1) + embed_html(content) + m.group(3), page, count=1)
    write_atomic(PAGE, new)


def current_embed():
    page = read(PAGE)
    m = PRE_RE.search(page)
    if not m:
        fail("could not find the <pre id=\"instructions-text\"> block")
    return m.group(2)


def main():
    args = sys.argv[1:]
    content = generate()
    if "--check" in args:
        ok = True
        try:
            on_disk = read(OUT)
        except FileNotFoundError:
            on_disk = None
        if on_disk != content:
            ok = False
            sys.stderr.write("build-portable-text: %s is out of date; regenerate it.\n" % OUT)
            if on_disk is not None:
                for a, b in zip(on_disk.split("\n"), content.split("\n")):
                    if a != b:
                        sys.stderr.write("  first diff:\n  - %r\n  + %r\n" % (a, b))
                        break
        want_embed = embed_html(content)
        if current_embed() != want_embed:
            ok = False
            sys.stderr.write("build-portable-text: the /instructions/ embed is out of date; run --embed.\n")
        sys.exit(0 if ok else 1)
    write_atomic(OUT, content)
    if "--embed" in args:
        embed(content)
    print("build-portable-text: wrote %s%s" % (OUT, " and embedded it in /instructions/" if "--embed" in args else ""))


if __name__ == "__main__":
    main()
