#!/usr/bin/env python3
"""Generate the extended portable Clean Language file from the skill source.

Reads cleanlanguage/SKILL.md and its references and writes a single
self-contained rendering, site/downloads/cleanlanguage.md, for pasting or
attaching to an assistant that cannot install a skill. The same bytes are also
written to site/downloads/cleanlanguage-29k.md: cleanlanguage.md is the canonical
name and always mirrors the largest size-labelled rendering, 29k for now. The
files are generated, never hand-edited; the sync gate checks them byte-for-byte.

Modes:
  (default)   write site/downloads/cleanlanguage.md and its byte-equal
              size-labelled twin cleanlanguage-29k.md atomically
  --embed     also rewrite the <pre id="instructions-text"> block in
              site/instructions/index.html with the HTML-escaped content
  --check     regenerate in memory, byte-compare both files and the embed,
              print the first difference, and exit 1 on any drift
"""
import html
import itertools
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILL = os.path.join(ROOT, "cleanlanguage", "SKILL.md")
REFDIR = os.path.join(ROOT, "cleanlanguage", "references")
OUT = os.path.join(ROOT, "site", "downloads", "cleanlanguage.md")
# cleanlanguage.md is the canonical name; it always mirrors the largest
# size-labelled rendering byte-for-byte. That is 29k for now.
OUT29 = os.path.join(ROOT, "site", "downloads", "cleanlanguage-29k.md")
PAGE = os.path.join(ROOT, "site", "instructions", "index.html")

OPENING = ("This is the Clean Language skill, written out as rules. Apply it "
           "to the writing in this conversation unless I tell you not to.")
MARKER = ("(Generated from cleanlanguage/SKILL.md and its references by "
          "tools/build-portable-text.py. Do not edit this file by hand.)")

# Reference consult order, and the prose pointer each inline link becomes.
REFS = [
    ("anti-patterns.md", "Anti-patterns", "the Anti-patterns section below"),
    ("context-modes.md", "Context modes", "the Context modes section below"),
    ("qa-checklist.md", "Quality checklist", "the Quality checklist section below"),
    ("examples.md", "Examples", "the Examples section below"),
]


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def strip_frontmatter(text):
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end == -1:
            fail("SKILL.md frontmatter is not closed")
        return text[end + 5:]
    return text


def fail(msg):
    sys.stderr.write("build-portable-text: %s\n" % msg)
    sys.exit(1)


def demote_headings(text):
    # Each reference keeps one document; demote so the whole file has one H1.
    # Skip fenced code blocks so a "# comment" inside one is not demoted, and
    # refuse an H6 that cannot be demoted within CommonMark's six levels.
    out = []
    in_fence = False
    for line in text.split("\n"):
        if re.match(r"^```", line):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence:
            m = re.match(r"^(#{1,6}) ", line)
            if m:
                if len(m.group(1)) >= 6:
                    fail("a reference heading is already H6 and cannot be demoted: %r" % line)
                line = "#" + line
        out.append(line)
    return "\n".join(out)


def generate():
    disk_refs = sorted(n for n in os.listdir(REFDIR) if n.endswith(".md"))
    known_refs = sorted(fname for fname, _title, _pointer in REFS)
    if disk_refs != known_refs:
        fail("the reference set changed; update REFS: on disk %s, REFS %s" % (disk_refs, known_refs))
    skill = read(SKILL)
    body = strip_frontmatter(skill)
    lines = body.split("\n")
    # The metadata block: the contiguous run of "Key: value" lines after the H1.
    # Body starts with "# Clean Language"; find it and the metadata that follows.
    try:
        h1 = next(i for i, l in enumerate(lines) if l.strip() == "# Clean Language")
    except StopIteration:
        fail("SKILL.md has no '# Clean Language' heading")
    meta = []
    j = h1 + 1
    while j < len(lines) and lines[j].strip() == "":
        j += 1
    while j < len(lines) and re.match(r"^[A-Za-z][A-Za-z ]*:\s", lines[j]):
        meta.append(lines[j])
        j += 1
    if not meta:
        fail("SKILL.md metadata block not found after the heading")
    # The rest of the body after the metadata block is the skill proper.
    rest = "\n".join(lines[j:]).lstrip("\n")
    # Rewrite the inline reference links to prose pointers.
    for fname, _title, pointer in REFS:
        rest = rest.replace("[references/%s](references/%s)" % (fname, fname), pointer)
    if "](references/" in rest:
        fail("an unrewritten references/ link remains in the skill body")
    # The reference appendix, headings demoted one level, in consult order.
    appendix = []
    for fname, _title, _pointer in REFS:
        ref = read(os.path.join(REFDIR, fname)).rstrip("\n")
        appendix.append(demote_headings(ref))
    parts = [
        OPENING,
        "",
        "# Clean Language",
        "",
        "\n".join(meta),
        "",
        MARKER,
        "",
        rest.rstrip("\n"),
        "",
        "\n\n".join(appendix),
    ]
    return "\n".join(parts).rstrip("\n") + "\n"


def embed_html(content):
    return html.escape(content, quote=False)


def write_atomic(path, text):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    os.replace(tmp, path)


PRE_RE = re.compile(
    r'(<pre id="instructions-text"[^>]*>)(.*?)(</pre>)', re.DOTALL)


def sole_pre_match(page):
    matches = list(PRE_RE.finditer(page))
    if len(matches) != 1:
        fail('expected exactly one <pre id="instructions-text"> block, found %d' % len(matches))
    return matches[0]


def embed(content):
    page = read(PAGE)
    m = sole_pre_match(page)
    new = page[:m.start()] + m.group(1) + embed_html(content) + m.group(3) + page[m.end():]
    write_atomic(PAGE, new)


def current_embed():
    return sole_pre_match(read(PAGE)).group(2)


def main():
    args = sys.argv[1:]
    content = generate()
    if "--check" in args:
        ok = True
        for target in (OUT, OUT29):
            try:
                on_disk = read(target)
            except FileNotFoundError:
                on_disk = None
            if on_disk != content:
                ok = False
                sys.stderr.write("build-portable-text: %s is out of date; regenerate it.\n" % target)
                if on_disk is not None:
                    for a, b in itertools.zip_longest(on_disk.split("\n"), content.split("\n")):
                        if a != b:
                            sys.stderr.write("  first diff:\n  - %r\n  + %r\n" % (a, b))
                            break
        want_embed = embed_html(content)
        if current_embed() != want_embed:
            ok = False
            sys.stderr.write("build-portable-text: the /instructions/ embed is out of date; run --embed.\n")
        sys.exit(0 if ok else 1)
    write_atomic(OUT, content)
    write_atomic(OUT29, content)
    if "--embed" in args:
        embed(content)
    print("build-portable-text: wrote %s and %s%s" % (OUT, OUT29, " and embedded it in /instructions/" if "--embed" in args else ""))


if __name__ == "__main__":
    main()
